version: '3'
services:
  pg:
    build: ./postgres/
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: gopher
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
    
  redis:
    image: redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=pass
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    ports:
       - 6379:6379
    

